apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convtemp
  template:
    metadata:
      labels:
        app: convtemp
    spec:
      containers:
        - name: meucontainer
          image: sofiapittasesso/conversao-temperatura:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meuservice
spec:
  selector:
    app: convtemp
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort
